BizzNEST/salinas-bizznest-scheduler

README.md

- Added Project Name
- Added Project Description
Start of the readme :)
Just writing the inital app name and small description
- None
- None
the Standard and Practices docs :)
Closes #3

[Docs]: Added Project Title + description

---

README.md

1. Added Development Process to README
It adds an explanation of the Development Process for the project.  
[Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
-used as a resource on how to format README
Closes #5

docs(readme): Added development process

---

README.md

_List Changes Introduced by this PR_
1. Project Set Up 
2. How to Run Project 
Create detailed instructions and format on how to run project 
Allows project to run smoothly due to clear instructions
What needs to be done before testing
[] Change database values in x collection to y.
How do the users test this change?
https://www.w3schools.com/html/html_styles.asp 
If this closes an issue, name it here. If it doesn't, remove this line
Closes #7 
Closes #8

docs(readme): Added project set up

---

README.md

1. Added Deployment Instructions
Describe where we will deploy website.
Closes #6

docs(readme): Added Deployment Instructions

---

README.md

Added Project requirements
To be descriptive on what this project entails
Closes #4

Docs: Added Project Requirements to README

---

index.html
src/style.css

**When you open your pull requests, remove the lines that start and end with underscores (\_)**
Added logo to footer 
Fixed mobile styles 
Closes #22

feat(footer): added footer

---

index.html
src/style.css

**When you open your pull requests, remove the lines that start and end with underscores (\_)**
_List Changes Introduced by this PR_
1. Added UI for generate and filter buttons
2. Added mobile compatibility 
3. Made it sticky to the top
UI for the generating schedules functionality and for the filtering system we need to implement.
Created button and select elements (to represent dropdown buttons) and incorporated our design.
Possible resources
-[How to use Checkbox inside Select Option using JavaScript ?](https://www.geeksforgeeks.org/how-to-use-checkbox-inside-select-option-using-javascript/)
-[How to Make a Multiselect Dropdown Menu](https://blog.hubspot.com/website/html-dropdown)
Continuation of #27

[Feat]: Added UI for Generate/Filter Buttons (currently nonfunctional)

---

.prettierignore
package.json

Updated Prettier Script
Script wasn't running on `index.html` as well as `css` + `html` files
`npm i`
`npm run format`

chore(prettier script): Updated prettier script to run on its root directory

---

src/documents/intern.json

Created Json File with the information of all interns such as name, department, location and weekly schedule. 
https://www.youtube.com/watch?v=iiADhChRriM&t=90s
Closes #17

[Feat]: Created intern JSON

---

src/scripts/filters.js
src/scripts/interns.js

By creating the function that filters interns by location, user can now select desired locations and the app will generate the interns in the selected locations
`getSelectedOptions` function 
`filterInternsByLocation` function checked the selected locations using a Set for efficient lookup
1. User will click location button and select the location/s of their choice in the drop down menu 
2. Click "Generate Schedule" button to see results 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter
Continues #30

Feat (filters): created filter by location

---

src/scripts/filters.js
src/scripts/interns.js
src/util/pair.js

1. In `filters.js` added the `filterByDepartment()` function.
2. In `pair.js` modified base case to account for array of interns that only contains one person.
3. In `interns.js` within the function `displayInternTable()` added a ternary operator to check if any pairs can be generated 
Select varying departments and see weather pairings generated match selected filters.
- [Javascript filter function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)
- [Ternary operators](https://www.geeksforgeeks.org/javascript-ternary-operator/)
Continues #30

[Feat] : Department filter for interns

---

src/scripts/interns.js

Added a search function within the `interns.js` to linearly search for interns.

feat(search): Added a function to search for interns

---

src/scripts/filters.js
src/scripts/interns.js

1. Added unique pairing to `filters.js`
2. Modified `interns.js` function `pairInterns()` to incorporate unique pairing
Implemented various functions for each unique pairing combination.
##TODO
- Select unique pairing filters
- Generate schedules and verify conditions were met within the pairings  * **Pairings at end of list may not met requirement but is usually just the last one.**
Closes #30

[Feat]: Unique pairing functionality

---

package.json
src/scripts/__tests__/hello_world.test.js
src/scripts/run-tests.js

A script and a directory to run / have all of our test through the terminal
1. Create a test in the `__tests__` directory (We usually call it `name-of-test.test.js`
2. In the console run `npm run test`
A way we can run and see all tests through the console.
Closes #57

[Feat]: Script to run all tests

---

package.json
src/documents/interns.json
src/scripts/__tests__/hello_world.test.js
src/scripts/interns.js
src/scripts/run-tests.js

- Changed the way we fetch interns so it's more readable
- Added methods to import interns
Needed a way to import interns for tests

[Fix]: Added a method to fetch interns through these tests as an example

---

index.html
src/constants/constants.js
src/scripts/filters.js
src/scripts/interns.js
src/style.css

Searching is now fixed and departments get rendered on click
- Better user experience and have less bugs :)

[Fix]: Fixing Searching for interns list

---

src/scripts/__tests__/filter-by-location-test.js

Tested the accuracy of the filter by location using `pairInterns(listOfOurLocations)` function and `filterByLocationTest(test)`
Make sure pair checker meets filter requirements
1. `pairInterns` function: transforms intern data, shuffles, filters by location, and pairs
2. function `filterByLocationTest(test)`: tests that the selected location retrieves pairing with the location selected 
Testing with multiple location like seen on the image. There percentage should be 100% for all 
Closes #53

[Test]: Filter by Location Test

---

index.html
src/app.js
src/scripts/exportCSV.js
src/style.css

_List Changes Introduced by this PR_
1. Added Export Button
2. HTML table to CSV file function
3. Added download functionality
Users can download a CSV file of the pairings of interns generated
- Added `exportCSV.js` to scripts folder
- 3 functions, one to display the button, one to convert table to CSV, one to download the file
Hover view:
After generating intern pairs scroll to the bottom of the list and click download button, CSV file named `InternPairs.csv` should be downloaded which then can be opened/imported to Google sheets or Excel.
- Followed this framework for creating a CSV from an HTML table since we organize our pairing information in a table.
- [How to export HTML table to CSV using JavaScript ?](https://www.geeksforgeeks.org/how-to-export-html-table-to-csv-using-javascript/ …

[Feat]: Export CSV file

---

src/scripts/__tests__/filterByLocation.test.js
src/scripts/__tests__/uniquePairing.test.js
src/scripts/run-tests.js
src/util/accuracy.js

fixed script to run on windows os. (Still works for mac as you can see above)
For people that are running the test on a different OS

[Feat]: Run-Test for windows

---

index.html
src/app.js
src/style.css

Added 'Add Pair' UI button 
It includes a seamless transition and changes color when you hover over it
When functional, this button will allow user to add their own pair.
Need to adjust button for mobile 
Closes #74

(Feat): Added UI for Add Pair Button (currently non-functional)

---

README.md

Updated project instructions, included 'run tests'

Docs: Update Instructions to Run Tests

---

src/app.js
src/scripts/edit.js
src/style.css

https://github.com/user-attachments/assets/7c496b3a-e6a3-42b1-a1b1-3ff4d7c5cad7
- Added / Removing pair functionality
- Some light refactoring
- For more override features

feat(edit.js): Added adding/removing pair functionality

---

src/style.css

wip(edit modal): Added potential modal size fix

---

src/constants/constants.js
src/scripts/interns.js

Added an emoji map for locations
To have more cute features for the generated table. 😄

Feat: Adding Emojis to generated list

---

src/style.css

Mobile View 
Tablet View
Closes #81

Fix: Fixing Visual Pairing Button style

---

src/documents/interns.json
src/util/sendEmail.js

1. Added emails to every intern
2. Fixed a few names 
3. Added Benjamin Schoolland
Formulates the emails from the asana and inserted into intern.json

Update JSON to include every intern email #84

---

README.md
src/constants/constants.js
src/scripts/__tests__/uniquePairing.test.js
src/scripts/edit.js
src/scripts/interns.js
src/style.css
src/util/uniquePairing.js

- **fix: fixing test with unique pairs with odd people**
- **feat(emails): Added a way to email pairs**
- A way to email the pairs :)

[Feat]: Added implementation to email pairs

---

.github/workflows/test.yml

[Bug]: GitHub Actions Tests Bug
